# values.yaml
# - Minimized CPU/Memory load, can fit into 3 CPU, 6 GB of RAM (barely)
# - Some services entirely removed, or scaled down to 1 replica.

global:
  # We will use custom ingress
  ingress:
    enabled: false
    configureCertmanager: false
    tls:
      enabled: false
  hosts:
    domain: k3d.local
    hostSuffix:
    https: false
    externalIP:
    ssh: ~
    gitlab:
      name: gitlab.k3d.local
      https: false
    minio:
      name: minio.k3d.local
      https: false
    registry:
      name: registry.k3d.local
      https: false
    tls:
      name: tls.k3d.local
      https: false
    smartcard:
      name: smartcard.k3d.local
      https: false
    kas:
      name: kas.k3d.local
      https: false
    pages:
      name: pages.k3d.local
      https: false

certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
