apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development 
  namespace: argocd
spec:
  description: Development Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the dev namespace in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cvernius
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: "https://kubernetes.default.svc"
  project: development
  source:
    path: manifests
    repoURL: "https://github.com/rimargri/cvernius.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
